---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Get disk space information
      command: "df -h"
      register: df_output
    - name: Export disk space information to CSV
      csv:
        columns:
          - Filesystem
          - Size
          - Used
          - Available
          - Use%
          - Mounted on
        data: "{{ df_output.stdout_lines }}"
        dest: /path/to/disk_space.csv
