---
- hosts: all
  gather_facts: yes
  tasks:
    - name: "Get disk space information"
      command: "df -h"
      register: df_output
    - name: Parse disk space information
      set_fact:
        disk_space: "{{ item.split() }}"
      with_items: "{{ df_output.stdout_lines }}"
    - name: "Export disk space information to CSV"
      csvfile:
        path: /path/to/disk_space.csv
        mode: w
        headers:
          - Filesystem
          - Size
          - Used
          - Available
          - Use%
          - Mounted on
        rows: "{{ disk_space }}"
