---
  - hosts: all
    gather_facts: true
    remote_user: ubuntu
    become: yes
    become_method: sudo
    tasks:
      - name: Get info on docker host and list images
        community.docker.docker_host_info:
          images: true
        register: result
      #- name: Print information about container
      - name: Prints two lines of messages, but only if there is an environment value set
        ansible.builtin.debug:
          #var: result.host_info
          msg:
          - " {{result.host_info}} "
          - " {{result.images}} "
