---
- hosts: all
  remote_user: coreyman
  become: yes
  become_method: sudo
  tasks:
   - name: nano install
     apt: name=nano state=present
   - name: vim install
     apt: name=vim state=present
   - name: htop install
     apt: name=htop state=present
   - name: speedtest-cli install
     apt: name=speedtest-cli state=present


#apt: name=nano state=absent
