---
- hosts: oracle
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
   - name: nano remove
     apt: name=nano state=present
   - name: vim install
     apt: name=vim state=present
