---
- name: "Onboard Linux Servers to Azure Arc-enabled servers with Public endpoint connectivity"
  hosts: all
  vars:
    azure:
      service_principal_id: '44a4ba54-b903-4fb5-a7f2-4945cc656e59'
      service_principal_secret: 'INSERT-SERVICE-PRINCIPAL-SECRET'
      resource_group: 'Arc-enabled-Canada'
      tenant_id: '0f35d426-eec2-4c88-8f44-e0f50498876d'
      subscription_id: '9463a1fe-17bf-434a-bda9-41520fe86e01'
      location: 'eastus'
  tasks:
  - name: {"checkIfdownloaded"}
    stat:
      path: /usr/bin/azcmagent
      get_attributes: False
      get_checksum: False
    register: azcmagent_lnx_downloaded
    when: ansible_system == 'Linux'

  - name: {"downloadConnectedMachineAgentLinuxANS"}
    become: yes
    get_url:
      url: https://aka.ms/azcmagent
      dest: ~/install_linux_azcmagent.sh
      mode: '700'
    when: (ansible_system == 'Linux') and (azcmagent_lnx_downloaded.stat.exists == false)

  - name: {"installConnectedMachineAgent"}
    become: yes
    shell: bash ~/install_linux_azcmagent.sh
    when: (ansible_system == 'Linux') and (not azcmagent_lnx_downloaded.stat.exists)

  - name: {"checkConnection"}
    become: true
    command:
     cmd: azcmagent check
    register: azcmagent_lnx_connected
    ignore_errors: yes
    when: ansible_system == 'Linux'
    failed_when: (azcmagent_lnx_connected.rc not in [ 0, 16 ])
    changed_when: False

  - name: {"connectToAzureArc"}
    become: yes
    shell: azcmagent connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"
    when:  (ansible_system == 'Linux') and (azcmagent_lnx_connected.rc is defined and azcmagent_lnx_connected.rc != 0)
