---
- name: Replace /etc/motd file
  hosts: all
  become: true
  #become_user: root
  tasks:
     - name: Update /etc/banner on webservers host group
       copy:
         content: 'This system is used for authroized employees only, COREYMAN LAB ONLY'
         dest: /etc/ssh/banner
     - name: enable ssh banner
       replace: dest=/etc/ssh/sshd_config regexp='^#?Banner none' replace='Banner /etc/ssh/banner' backup=yes
       register: banner_enabled      
     - name: ssh restart
       service: name=sshd state=restarted
       when: banner_enabled.changed or root_disabled.changed

