---
- hosts: oracle
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name:
      apt:
       update_cache: yes
    - name:
      command: apt list --upgradable
      register: updates
    - debug: var=updates.stdout_lines