---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
    vars_prompt:
    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your password?
  tasks:
  - name: Print a message
    ansible.builtin.debug:
      msg: 'Logging in as {{ username }}'
  - name: Clone the template
    vmware_guest:
      hostname: 192.0.2.44
      username: administrator@vsphere.local
      password: vmware
      validate_certs: False
      name: testvm_2
      template: template_el7
      datacenter: DC1
      folder: /DC1/vm
      state: poweredon
      wait_for_ip_address: yes